---
- name: Dev requirements
  yum: name={{ item }} state=present
  with_items:
  - gcc
  - libffi-devel
  - python2-pip
  - python-virtualenv
  - openssl-devel

#- name: Install python packages from pipy
#  pip: name={{ item.name }} version={{ item.version }}
#  with_items: "{{ py_packages }}"
