# This task is equivalent to running the following command
# in files/centos7:
#
# docker build -t test:latest .
#
---
- name: Build image
  docker_image: name=test tag=latest path="{{ role_path }}/files/centos7/"
