#
# ansible-playbook docker-ansible-test.yml
#
# If need be, root password to containers is "docker.io"
#
# To inspect, login directly to the container via docker:
#
# docker exec -i -t <container_name> /bin/bash
#
---
- name: Bring up role inspector container
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    inventory:
    - name: role_tester
      image: "base:latest"
  roles:
  - { role: docker_build_image }
  - { role: provision_containers, provision_docker_inventory_group: "{{ inventory }}" }

- name: Apply webserver role to container
  hosts: just_created
  connection: docker
  roles:
  - webserver
